experiment: tutorial_demo13
method: learning_vectors
max_levels: 100
threshold: 0.0
max_epsilon: 2
plot_gifs: false

train_config:
  K: 100
  nhid: 10
  lr: 0.0001
  wd: 0.000001
  dropout: 0.2
  # epochs_per_level: 1
  initial_epochs: 3
  min_epochs: 1
  max_epoch_interval: 1
  loss_window: 10
  loss_threshold: 0.002
  alpha: 1.0
  compression_method: svd
  epsilon_schedule_power: 0.01
  # GNN_type: GCN
  GNN_type: SAGE
  num_layers: 4
  use_edge_weights: True


alert_thresholds:
  - 0.51
  - 0.51
normal_thresholds:
  - 0.51
  - 0.51

pattern_split_config:
  train_ratio: 0.2
