experiment: tutorial_demo13
method: variation_edges    # learning_vectors, learning_bases, variation_edges, variation_bases, variation_neighborhood, variation_star
remove_overlaps: False
max_levels: 10
max_epsilon: 50
plot_gifs: false

train_config:
  K: 100
  nhid: 8
  lr: 0.001
  wd: 0.000001
  dropout: 0.1
  initial_epochs: 3
  min_epochs: 1
  max_epoch_interval: 1
  loss_window: 10
  loss_threshold: 0.002
  alpha: 1.0
  compression_method: svd
  epsilon_schedule_power: 0.04
  GNN_type: DGCN
  num_layers: 4
  use_edge_weights: False
  coarsening_weight: 0.0
  use_labels_for_coarsening: False
  use_super_node_loss: False



alert_thresholds:
  - 0.51
  - 0.51
normal_thresholds:
  - 0.51
  - 0.51

pattern_split_config:
  train_ratio: 0.2
