experiment: tutorial_demo12
method: learning_vectors
max_levels: 100
max_epsilon: 5
plot_gifs: false

train_config:
  K: 100
  nhid: 10
  lr: 0.001
  wd: 0.00001
  dropout: 0.25
  initial_epochs: 3
  min_epochs: 1
  max_epoch_interval: 1
  loss_window: 10
  loss_threshold: 0.002
  alpha: 1.0
  compression_method: svd
  epsilon_schedule_power: 0.05
  GNN_type: DGCN
  num_layers: 4
  use_edge_weights: False
  coarsening_weight: 10.0
  use_labels_for_coarsening: False


alert_thresholds:
  - 0.51
  - 0.51
normal_thresholds:
  - 0.51
  - 0.51

pattern_split_config:
  train_ratio: 0.2
